#!/bin/bash

export VAULT_ADDR='https://thinktopic.com:8200'

echo "Requesting access to S3 maven repository..."
creds=`vault read aws/sts/core-sts`
access_key=$(echo "$creds" | awk '/access_key/ { print $2 }')
secret_key=$(echo "$creds" | awk '/secret_key/ { print $2 }')
session_token=$(echo "$creds" | awk '/security_token/ { print $2 }')

echo "export AWS_ACCESS_KEY_ID=$access_key"
echo "export AWS_SECRET_ACCESS_KEY=$secret_key"
echo "export AWS_SESSION_TOKEN=$session_token"

export AWS_ACCESS_KEY_ID=$access_key
export AWS_SECRET_ACCESS_KEY=$secret_key
export AWS_SESSION_TOKEN=$session_token

